.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
INFO.md

---
name: Pull Request
about: Create templates to standardize merging
title: Collaboration Templates
labels: improvement
assignees: 
---
Created templates for:

Issue and pull request templates

---

web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/resources/templates/partner/dashboard.html

---
title: ''
labels: ''
assignees: ''
---
Added Partner dashboard

ADP-76 Partner Dashboard

---

config/src/main/java/com/wilma/config/web/UserConfiguration.java
web/src/main/resources/static/js/scripts.js
web/src/main/resources/templates/fragments/marketplace-tables.html

---
title: 'Correct marketplace tables and table functions'
labels: ''
assignees: 'Nathan Snow, Rory Allen'
---
**`This PR fixes ADP-77`**
Split the JavaScript functions to enable partners and educators to have different table results in the jobs & placements page
Enabled the "expressions of interest" menu link for partners
Corrected JavaScript filter function for partner positions to include searching the description (not status)

Correct marketplace tables - Fixes ADP-77

---

entity/src/main/java/com/wilma/entity/Tag.java
entity/src/main/java/com/wilma/entity/forum/ForumContent.java
entity/src/main/java/com/wilma/entity/forum/Post.java
entity/src/main/java/com/wilma/entity/forum/Reply.java
entity/src/main/java/com/wilma/entity/positions/Job.java
entity/src/main/java/com/wilma/entity/positions/Placement.java
entity/src/main/java/com/wilma/entity/positions/Position.java
entity/src/main/java/com/wilma/entity/users/Partner.java
entity/src/main/java/com/wilma/entity/users/RemoteClient.java
entity/src/main/java/com/wilma/entity/users/Role.java
entity/src/main/java/com/wilma/entity/users/UserAccount.java
service/src/main/java/com/wilma/service/SeedDataService.java
web/src/main/resources/templates/fragments/forum.html

Fixed bugs that were resulting from a couple of incorrect object relationships

Refactor DB tables and ORM relationships

---

web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/StudentPortalController.java
web/src/main/resources/templates/educator/dashboard.html
web/src/main/resources/templates/partner/dashboard.html
web/src/main/resources/templates/partner/marketplace.html

---
title: 'Development pre-merge tweaks and refactoring'
labels: ''
assignees: ''
---

Development pre-merge tweaks and refactoring

---

pom.xml
repository/src/main/java/com/wilma/repository/PositionApplicationRepository.java
service/src/main/java/com/wilma/service/positions/ApplicationNotificationService.java
service/src/main/java/com/wilma/service/positions/PositionService.java
web/src/main/java/com/wilma/web/controller/api/v1/PartnerController.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/resources/application.yml
web/src/test/java/com/wilma/service/positions/ApplicationNotificationServiceTest.java
web/src/test/java/com/wilma/web/controller/web/portal/StudentPortalControllerTest.java
web/src/test/resources/application.yml

---
title: ADP-117 Partners get notified of new job/placement applications (batch emails each day)
labels: 
---
*Note:* Project dependencies are also updated due to discovered vulnerabilities

ADP-117 Partners get notified of new job/placement applications (batch emails each day)

---

entity/src/main/java/com/wilma/entity/positions/ExpressionOfInterest.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/resources/templates/fragments/expressions-of-interest-tables.html
web/src/main/resources/templates/partner/expressions-of-interest.html

---
name: ADP-119 Add RTS and EOI tables to Partner EOI Page
title: 'ADP-119 Add RTS and EOI tables to Partner EOI Page'
---
Add Expression Of Interest and Request To Supply table UI to Partner Expressions of Interest Page.

ADP-119 Add RTS and EOI tables to Partner EOI Page

---

.gitignore
config/src/main/java/com/wilma/config/mail/MailConfiguration.java
web/src/main/resources/application.yml
web/src/test/java/com/wilma/service/positions/ApplicationNotificationServiceTest.java
web/src/test/resources/application.yml

---
title: Email Account Fix
labels: 
---
As per the recent email provider security issues surrounding SMTP connection, 
I switched to gmail for a more secure and consistent service. The email tests are now functioning again.
**NOTE:** You will need to supply the mail configuration when running the email tests or running maven goals that include running the test (such as the "package" goal) in the test directory `application.yml` file
I will supply updated `dev` and `prod` run configuration files that include the email config.
Fixes #46

Email Account Fix

---

entity/src/main/java/com/wilma/entity/users/Educator.java
entity/src/main/java/com/wilma/entity/users/Partner.java
entity/src/main/java/com/wilma/entity/users/UserAccount.java
service/src/main/java/com/wilma/service/SeedDataService.java
service/src/main/java/com/wilma/service/UserService.java
service/src/main/java/com/wilma/service/docs/DocumentService.java
web/src/main/java/com/wilma/web/controller/api/v1/FileController.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/resources/application-dev.yml
web/src/main/resources/templates/educator/profile.html
web/src/main/resources/templates/fragments/navigation.html
web/src/main/resources/templates/fragments/profile-forms.html

---
title: ADP-111 Educator-enable-user-profiles
labels: 
---

ADP-111 Educator-enable-user-profiles

---

entity/src/main/java/com/wilma/entity/users/Partner.java
service/src/main/java/com/wilma/service/SeedDataService.java
service/src/main/java/com/wilma/service/UserService.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/resources/application-dev.yml
web/src/main/resources/templates/fragments/profile-forms.html
web/src/main/resources/templates/partner/profile.html

---
title: ADP-112 Partner-enable-user-profiles
labels: 
---

ADP-112 Partner-enable-user-profiles

---

entity/src/main/java/com/wilma/entity/users/Student.java
service/src/main/java/com/wilma/service/SeedDataService.java
service/src/main/java/com/wilma/service/UserService.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/StudentPortalController.java
web/src/main/resources/application-dev.yml
web/src/main/resources/templates/fragments/profile-forms.html
web/src/main/resources/templates/student/profile.html

---
title: ADP-113 Student-enable-user-profiles
labels: 
---

ADP-113 Student-enable-user-profiles

---

config/src/main/java/com/wilma/config/mail/MailConfiguration.java
entity/src/main/java/com/wilma/entity/contact/ContactForm.java
service/src/main/java/com/wilma/service/positions/ApplicationNotificationService.java
web/src/main/java/com/wilma/web/controller/web/SiteController.java
web/src/main/resources/application.yml
web/src/main/resources/templates/contact.html
web/src/main/resources/templates/fragments/educatorForm.html
web/src/main/resources/templates/fragments/expressions-of-interest-tables.html
web/src/test/resources/application.yml

---
name: Pull Request
title: 'ADP-94 Contact Form'
labels: ''
assignees: @nick-mcguffin 
---
Implements email functionality for the contact us form. An email will be sent to the WILMA dev email when the form is submitted in the following format: 
From: Test User
Email: test@email.com
Details: This email works as expected.

Adp 94 contact form

---

entity/src/main/java/com/wilma/entity/users/Educator.java
entity/src/main/java/com/wilma/entity/users/Partner.java
entity/src/main/java/com/wilma/entity/users/Student.java
entity/src/main/java/com/wilma/entity/users/UserAccount.java
service/src/main/java/com/wilma/service/SeedDataService.java
service/src/main/java/com/wilma/service/UserService.java
service/src/main/java/com/wilma/service/docs/DocumentService.java
web/src/main/java/com/wilma/web/controller/api/v1/FileController.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/StudentPortalController.java
web/src/main/resources/application-dev.yml
web/src/main/resources/templates/educator/profile.html
web/src/main/resources/templates/fragments/navigation.html
web/src/main/resources/templates/fragments/profile-forms.html
web/src/main/resources/templates/partner/profile.html
web/src/main/resources/templates/student/profile.html

---
title: ADP-110 Enable-user-profiles
labels: 
---
___
**NOTE:** When in the `dev` profile ***you will need to specify the user you're using*** in the **`application-dev.yml`** file
```yaml
profiles:
profile-name: DEV
dev-username: student # <-- student, partner, or educator
```
___

ADP-110 Enable-user-profiles

---

entity/src/main/java/com/wilma/entity/users/ConfirmationToken.java
entity/src/main/java/com/wilma/entity/users/UserAccount.java
repository/src/main/java/com/wilma/repository/ConfirmationTokenRepository.java
repository/src/main/java/com/wilma/repository/UserAccountRepository.java
service/src/main/java/com/wilma/service/UserRegistrationService.java
service/src/main/java/com/wilma/service/mail/Mailer.java
service/src/main/java/com/wilma/service/mail/MailerImpl.java
service/src/main/java/com/wilma/service/positions/ApplicationNotificationService.java
web/src/main/java/com/wilma/web/controller/web/SiteController.java
web/src/main/resources/application-prod.yml
web/src/main/resources/templates/account-verified.html
web/src/main/resources/templates/error.html

---
title: 'ADP-93-Verify-User-Emails'
labels: ''
assignees: @nick-mcguffin 
---
Users now receive a verification email to accept upon creating an account.
New user accounts cannot be created with existing usernames or emails.

ADP-93-Verify-User-Emails

---

entity/src/main/java/com/wilma/entity/dto/ExpressionOfInterestDTO.java
entity/src/main/java/com/wilma/entity/positions/ExpressionOfInterest.java
service/src/main/java/com/wilma/service/positions/EOIService.java
service/src/main/java/com/wilma/service/positions/PositionService.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/resources/templates/educator/edit-expression-of-interest.html
web/src/main/resources/templates/educator/expressions-of-interest.html
web/src/main/resources/templates/educator/new-expression-of-interest.html
web/src/main/resources/templates/fragments/expressions-of-interest-tables.html
web/src/main/resources/templates/fragments/position-forms.html
web/src/main/resources/templates/partner/expressions-of-interest.html
web/src/main/resources/templates/partner/marketplace.html
web/src/main/resources/templates/partner/new-placement-from-eoi.html

---
title: 'ADP-109-enable-partner-expression-of-interest'
labels: ''
assignees: ''
---
NB: There is no seed data, if needed you can create an eoi from educator/expression-of-interest. Dummy data stored in the controller will not work as the conversion calls for the eoi entity from the db.

ADP-109-enable-partner-expression-of-interest

---

entity/src/main/java/com/wilma/entity/dto/ExpressionOfInterestDTO.java
entity/src/main/java/com/wilma/entity/positions/ExpressionOfInterest.java
service/src/main/java/com/wilma/service/positions/EOIService.java
service/src/main/java/com/wilma/service/positions/PositionService.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/resources/templates/educator/edit-expression-of-interest.html
web/src/main/resources/templates/educator/expressions-of-interest.html
web/src/main/resources/templates/educator/new-expression-of-interest.html
web/src/main/resources/templates/fragments/expressions-of-interest-tables.html
web/src/main/resources/templates/fragments/position-forms.html

---
title: 'ADP-107-enable-educator-expressions-of-interest'
labels: ''
assignees: ''
---
This submission does not include

ADP-107-enable-educator-expressions-of-interest

---

web/src/test/java/com/wilma/service/LiveServiceTests.java
web/src/test/java/com/wilma/web/controller/web/portal/EducatorPortalControllerTest.java
web/src/test/java/com/wilma/web/controller/web/portal/PartnerPortalControllerTest.java
web/src/test/resources/application-dev.yml
web/src/test/resources/application.yml

---
title: Update Tests
labels: 
---
Simple changes to update the test data & dependencies to match the recent changes.  

Test updates after recent merges

---

entity/src/main/java/com/wilma/entity/positions/Placement.java
service/src/main/java/com/wilma/service/positions/PositionService.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/resources/templates/educator/marketplace.html
web/src/main/resources/templates/educator/view-review.html
web/src/main/resources/templates/fragments/marketplace-tables.html
web/src/main/resources/templates/fragments/review-forms.html

---
title: 'Educator Reviews'
labels: 'Reviews'
assignees: 'Nathan Downes'
---
Added Student Profile Design
- [x ] You are NOT attempting to merge into the `master` branch
- [ x] You are requesting to merge your branch into the `development` branch or one of its sub-branches
- [ x] Your code compiles and runs without errors (on as many operating systems as practicable
- [x ] Code has sufficient Javadoc comments (giving examples where needed)
- [x ] Code is clear and readable, being sure to use meaningful names and effective whitespace
- [x ] Appropriate [naming …

Reviews pull requests

---

entity/src/main/java/com/wilma/entity/positions/Job.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/resources/templates/fragments/expressions-of-interest-tables.html
web/src/main/resources/templates/fragments/marketplace-tables.html

---
title: ADP-142 Delete Function
labels: 
---
Added delete functionality for...
A bug was detected and fixed by adding a `completed` boolean in the `Job` class.
Not the best solution but it works, [read more about it here](https://github.com/nick-mcguffin/Application-Development-Project/commit/e53383bd4f020ba861fe88d3bc858909cb7bd57e#r85583044)

ADP-142 Delete Function

---

web/src/main/java/com/wilma/web/controller/web/portal/StudentPortalController.java
web/src/main/resources/static/css/common.css
web/src/main/resources/templates/fragments/educatorForm.html
web/src/main/resources/templates/fragments/expressions-of-interest-tables.html
web/src/main/resources/templates/fragments/forum.html
web/src/main/resources/templates/fragments/partnerForm.html
web/src/main/resources/templates/fragments/position-details.html
web/src/main/resources/templates/fragments/position-forms.html
web/src/main/resources/templates/fragments/profile-forms.html
web/src/main/resources/templates/fragments/studentForm.html

---
title: ADP-92 Validate User Input
labels: ''
assignees: @nick-mcguffin 
---
- [x ] Feature 
- [x ] Improvement 
Basic Validation - prevent null values being entered throughout application and limit lengths of certain inputs.
Also a cheeky student profile edit bugfix one liner.

ADP-92 Validate User Input

---

web/src/main/java/com/wilma/web/controller/web/SiteController.java
web/src/main/java/com/wilma/web/controller/web/portal/EducatorPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/PartnerPortalController.java
web/src/main/java/com/wilma/web/controller/web/portal/StudentPortalController.java
web/src/main/resources/static/css/common.css
web/src/main/resources/templates/fragments/educatorForm.html
web/src/main/resources/templates/fragments/expressions-of-interest-tables.html
web/src/main/resources/templates/fragments/forum.html
web/src/main/resources/templates/fragments/partnerForm.html
web/src/main/resources/templates/fragments/position-details.html
web/src/main/resources/templates/fragments/position-forms.html
web/src/main/resources/templates/fragments/profile-forms.html
web/src/main/resources/templates/fragments/studentForm.html

---
title: Controller Refactor
labels: 
---
Refactored `currentPage` values to fix menu inconsistencies 
Regrouped methods

Controller Refactor
